server:
  port: 6789
  servlet:
    context-path: /shiro
  tomcat:
    uri-encoding: UTF-8

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.mk.shiro.model

# 数据库和Druid连接池配置
spring:
  datasource:
    name: shiro
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: hzsl@1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 3
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      enable: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 国际化设置
  messages:
    basename: i18n/messages
  # 全局编码设置 http://www.pianshen.com/article/9505282218/
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  # redis配置
  redis:
    host: 192.168.1.125
    port: 6379
    lettuce:
      pool:
        max-wait: 30000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池最大空闲连接
        min-idle: 0 # 连接池最小空闲连接
    timeout: 1000 # 连接超时
    # 使用指定redis库
    database: 0

# 配置日志打印等级
logging:
#  level.com.mk.shiro.mapper: debug
  level:
    com.mk.shiro.mapper: debug
  config: classpath:logback-spring.xml
  file:
    path: D:\date4truth\mk4_springboot_shiro


